lib/funny_web/router.ex
defmodule FunnyWeb.Router do
  use FunnyWeb, :router

  # Our pipeline implements "maybe" authenticated. We'll use the `:ensure_auth` below for when we need to make sure someone is logged in.
  pipeline :auth do
    plug Funny.Accounts.Pipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :browser do
    plug :accepts, ["json", "html"]
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FunnyWeb do
    pipe_through [:browser, :auth]

    get "/funny-service", PageController, :test
    get "/login", AppController, :sign_in
    post "/login", AppController, :login

    get "/forgot-password", AppController, :forgot_password
    post "/email_new_password", AppController, :email_new_password

    get "/register", AppController, :register
    post "/register", AppController, :register_post
  end

  scope "/", FunnyWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    scope "/images" do
      get "/:family_id/:file", AppController, :get_file
    end

    get "/add-family", AppController, :add_family
    post "/add-family", AppController, :add_family_post

    get "/add-family-member", AppController, :add_family_member
    post "/add-family-member", AppController, :add_family_member_post

    get "/settings", AppController, :settings
    get "/change_password", AppController, :change_password
    post "/change_password", AppController, :post_change_password

    post "/comment", AppController, :post_comment
    post "/registersubscription", AppController, :register_subscription

    get "/", AppController, :index
    resources "/jokes", JokeController
    # post "/register", AuthController, :register
    get "/logout", AuthController, :logout
  end

  scope "/api", FunnyWeb do
    pipe_through [:api, :auth, :ensure_auth]

    resources "/persons", PersonController, only: [:index, :update, :edit]
    resources "/jokes", JokeController, except: [:update]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:fetch_session, :protect_from_forgery]
      live_dashboard "/dashboard", metrics: FunnyWeb.Telemetry
    end
  end
end

lib/funny_web/templates/app/add_family.html.eex
hey welcome. all posts belong to a family. let's add a new family for you

<div class="row justify-content-center mb-5">
  <div class="col-auto"> 

    <%= form_for @changeset, @action, fn f -> %>
      <div class="form-group mb-2">
        <%= label f, :name, "Family Last Name", class: "control-label" %>
        <%= text_input f, :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= submit "Add new family", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

lib/funny_web/templates/app/add_family_member.html.eex
Add a new member to the <%= @fam_name %> family

<div class="row justify-content-center mb-5">
  <div class="col-auto"> 

    <%= form_for @changeset, @action, fn f -> %>

      <div class="form-group">
        <%= label f, :name, class: "control-label" %>
        <%= text_input f, :name, class: "form-control" %>
        <%= error_tag f, :name %>
      </div>

      <div class="form-group">
        <%= submit "Add member", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

lib/funny_web/templates/app/change_password.html.eex
<div class="row justify-content-center mb-5">
  <div class="col-lg-4 col-md-6 col-sm-8 spinner-center"> 

    <%= if @invalid_login do %>
      <div class="alert alert-danger" role="alert">
        Unable to login. Double check your email and password
      </div>
    <% end %>

    <%= form_for @changeset, @action, fn f -> %>

      <div class="form-group mb-3">
        <%= label f, :old_password, class: "control-label" %>
        <%= password_input f, :old_password, class: "form-control #{is_invalid_check(f, :old_password)}", "aria-describedby": input_id(f, :old_password) %>
        <%= error_tag f, :old_password %>
      </div>

      <div class="form-group mb-4">
        <%= label f, :new_password, class: "control-label" %>
        <%= password_input f, :new_password, 
                    class: "form-control #{is_invalid_check(f, :new_password)}", 
                    "aria-describedby": input_id(f, :new_password)
        %>
        <%= error_tag f, :new_password %>
      </div>

      <div class="form-group d-grid gap-2">
        <%= submit "Change Password", class: "btn btn-primary mb-3", onclick: "trigger_login_loading()" %>
      </div>
    <% end %>

    <div class="spinner-border spinny" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>

  </div>
</div>

lib/funny_web/templates/app/forgot_password.html.eex
faggehet about it

<div class="row justify-content-center mb-5">
  <div class="col-auto"> 

    THIS ISNT HOOKED UP JUST YET
    <%= form_for @conn, Routes.app_path(@conn, :email_new_password), fn f -> %>
      <div class="form-group">
        <%= label f, :email, class: "control-label" %>
        <%= text_input f, :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= submit "Email new password", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

lib/funny_web/templates/app/index.html.eex
<div class="row justify-content-center mb-5">
  <div class="col-auto"> 
    <%= if @jokes == [] do %>
      Hey looks like your family hasn't logged any jokes yet
      <a class="nav-link" href="/jokes/new">Add one now</a>
    <% else %>
      <%= for {joke, index} <- Enum.with_index(@jokes) do %>
        <%= link to: Routes.joke_path(@conn, :show, joke.id), class: "card-link" do %>
          <div class="card mt-3" style="cursor: pointer; width: 20rem;">
            <div class="card-body">
              <%= if joke.image_url != nil do %>
                <%= if index < 4 do %>
                  <%= img_tag "/images/#{joke.image_url}" , [style: "max-width: 100%"]%>
                <% else %>
                  <%= lazy_img "/images/#{joke.image_url}" , [style: "max-width: 100%"]%>
                <% end %>
              <% end %>
              <p class="card-text">
              <%= text_to_html(joke.content) %>
              </p>
            </div>
            <div class="card-body ">
              <h4 class="card-title text-end">
                <%= joke.person.name %>
              </h4>
                <%= if joke.comments != [] do %>
                  <div class="card-text text-muted">
                    <%= comment_svg() %><%= length(joke.comments) %>
                  </div>
                <% end %>
            </div>
          </div>
        <% end %> 
      <% end %> 
    <% end %> 

  </div>
</div>

lib/funny_web/templates/app/register.html.eex
<div class="row justify-content-center mb-5">
  <div class="col-lg-6 col-sm-10"> 

    <%= form_for @changeset, @action, fn f -> %>

      <div class="form-group">
        <%= label f, :name, "First Name", class: "control-label" %>
        <%= text_input f, :name, class: "form-control #{is_invalid_check(f, :name)}",
                    "aria-describedby": input_id(f, :name)
        %>
        <%= error_tag f, :name %>
      </div>
      <div class="form-group">
        <%= label f, :email, class: "control-label" %>
        <%= text_input f, :email, class: "form-control #{is_invalid_check(f, :email)}", "aria-describedby": input_id(f, :email)
        %>
        <%= error_tag f, :email %>
      </div>

      <div class="form-group">
        <%= label f, :password, class: "control-label #{is_invalid_check(f, :password)}" ,
                    "aria-describedby": input_id(f, :password)
        %>
        <%= password_input f, :password, class: "form-control #{is_invalid_check(f, :password)}", "aria-describedby": input_id(f, :email) %>
        <%= error_tag f, :password %>
      </div>

      <div class="form-group">
        <%= submit "Register", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

lib/funny_web/templates/app/settings.html.eex
<h1 class="h1 mb-3">Settings</h1>

<h2 class="h3">
  the <%= @fam_name %> family
</h2>

<div class="row justify-content-center mb-5">
  <div class="col-auto"> 
      <%= for member <- @fam_members do %> 
        <div> 
          <%= member.name %>
        </div> 
      <% end %>
  </div> 

  <div> 
    <div><%= link "Add family member", 
              to: Routes.app_path(@conn, :add_family_member), 
              class: "btn btn-secondary mb-3" %></div>
    <div><%= link "Change Password", 
              to: Routes.app_path(@conn, :change_password), 
              class: "btn btn-secondary" %></div>
  </div> 
</div> 

lib/funny_web/templates/app/sign_in.html.eex
<div class="row justify-content-center mb-5">
  <div class="col-lg-4 col-md-6 col-sm-8 spinner-center"> 

    <%= if @invalid_login do %>
      <div class="alert alert-danger" role="alert">
        Unable to login. Double check your email and password
      </div>
    <% end %>

    <%= form_for @changeset, @action, fn f -> %>

      <div class="form-group mb-3">
        <%= label f, :email, class: "control-label" %>
        <%= text_input f, :email, class: "form-control #{is_invalid_check(f, :email)}", "aria-describedby": input_id(f, :email) %>
        <%= error_tag f, :email %>
      </div>

      <div class="form-group mb-4">
        <%= label f, :password, class: "control-label" %>
        <%= password_input f, :password, 
                    class: "form-control #{is_invalid_check(f, :password)}", 
                    "aria-describedby": input_id(f, :password)
        %>
        <%= error_tag f, :password %>
      </div>

      <div class="form-group d-grid gap-2">
        <%= submit "Sign in", class: "btn btn-primary mb-3", onclick: "trigger_login_loading()" %>
        <%= link "Forgot Password", to: Routes.app_path(@conn, :forgot_password),  class: "btn btn-outline-secondary" %>
        <%= link "Register", to: Routes.app_path(@conn, :register), class: "btn btn-outline-secondary" %>
      </div>
    <% end %>
    <div class="spinner-border spinny" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>